import type { Property, TrustBreakdown } from "@/types";

import { getMockPropertyImage } from "@/lib/mockImages";

function trustBreakdown(overall: number): TrustBreakdown {
  const factor = overall / 100;
  return {
    ownershipVerified: Math.round(85 * factor),
    agentVerified: Math.round(90 * factor),
    addressVerified: Math.round(88 * factor),
    gpsVerified: Math.round(82 * factor),
    photoIntegrity: Math.round(92 * factor),
    noDuplicateListing: Math.round(95 * factor),
    priceVsMarket: Math.round(80 * factor),
  };
}

export const mockProperties: Property[] = [
  {
    id: "prop-001",
    title: "The Emerald Courtyard Duplex",
    description:
      "A stunning 4-bedroom duplex in Lekki Phase 1 with modern finishes, 24-hour power, and a private courtyard.",
    price: 185000000,
    priceType: "sale",
    bedrooms: 4,
    bathrooms: 5,
    squareFootage: 3200,
    address: "12 Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    country: "Nigeria",
    latitude: 6.4474,
    longitude: 3.4700,
    images: [getMockPropertyImage(0)],
    trustScore: 96,
    trustBreakdown: trustBreakdown(96),
    amenities: [
      { name: "Swimming Pool", icon: "pool", available: true },
      { name: "Generator", icon: "zap", available: true },
    ],
    powerSupplyHours: 24,
    waterSupply: true,
    agentId: "agent-001",
    isVerified: true,
    isOwnershipVerified: true,
    isPriceReduced: false,
    listedAt: new Date("2026-05-12"),
    createdAt: new Date("2026-05-01"),
  },
  {
    id: "prop-002",
    title: "Skyline Terrace Apartment",
    description:
      "Premium 3-bedroom apartment with panoramic city views in Victoria Island.",
    price: 4500000,
    priceType: "rent",
    bedrooms: 3,
    bathrooms: 3,
    squareFootage: 1800,
    address: "8 Akin Adesola Street",
    city: "Victoria Island",
    state: "Lagos",
    country: "Nigeria",
    latitude: 6.4281,
    longitude: 3.4219,
    images: [getMockPropertyImage(1)],
    trustScore: 91,
    trustBreakdown: trustBreakdown(91),
    amenities: [
      { name: "Gym", icon: "dumbbell", available: true },
      { name: "Parking", icon: "car", available: true },
    ],
    powerSupplyHours: 20,
    waterSupply: true,
    agentId: "agent-002",
    isVerified: true,
    isOwnershipVerified: true,
    isPriceReduced: true,
    listedAt: new Date("2026-05-18"),
    createdAt: new Date("2026-05-10"),
  },
  {
    id: "prop-003",
    title: "Maitama Garden Villa",
    description:
      "Spacious 5-bedroom villa with landscaped gardens in the heart of Maitama.",
    price: 320000000,
    priceType: "sale",
    bedrooms: 5,
    bathrooms: 6,
    squareFootage: 4500,
    address: "3 Aguiyi Ironsi Street",
    city: "Maitama",
    state: "Abuja",
    country: "Nigeria",
    latitude: 9.0820,
    longitude: 7.4913,
    images: [getMockPropertyImage(2)],
    trustScore: 88,
    trustBreakdown: trustBreakdown(88),
    amenities: [
      { name: "Garden", icon: "trees", available: true },
      { name: "Security", icon: "shield", available: true },
    ],
    powerSupplyHours: 22,
    waterSupply: true,
    agentId: "agent-003",
    isVerified: true,
    isOwnershipVerified: false,
    isPriceReduced: false,
    listedAt: new Date("2026-04-28"),
    createdAt: new Date("2026-04-20"),
  },
  {
    id: "prop-004",
    title: "GRA Executive Bungalow",
    description:
      "Well-maintained 3-bedroom bungalow in Port Harcourt GRA with ample parking.",
    price: 95000000,
    priceType: "sale",
    bedrooms: 3,
    bathrooms: 4,
    squareFootage: 2400,
    address: "15 Harold Wilson Drive",
    city: "Port Harcourt",
    state: "Rivers",
    country: "Nigeria",
    latitude: 4.8156,
    longitude: 7.0498,
    images: [getMockPropertyImage(3)],
    trustScore: 78,
    trustBreakdown: trustBreakdown(78),
    amenities: [
      { name: "Parking", icon: "car", available: true },
      { name: "BQ", icon: "home", available: true },
    ],
    powerSupplyHours: 16,
    waterSupply: true,
    agentId: "agent-004",
    isVerified: false,
    isOwnershipVerified: false,
    isPriceReduced: false,
    listedAt: new Date("2026-05-05"),
    createdAt: new Date("2026-04-30"),
  },
  {
    id: "prop-005",
    title: "Bodija Luxury Shortlet",
    description:
      "Fully furnished 2-bedroom shortlet with smart home features in Bodija.",
    price: 85000,
    priceType: "shortlet",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 1200,
    address: "22 Awolowo Avenue",
    city: "Ibadan",
    state: "Oyo",
    country: "Nigeria",
    latitude: 7.4210,
    longitude: 3.9015,
    images: [getMockPropertyImage(4)],
    trustScore: 72,
    trustBreakdown: trustBreakdown(72),
    amenities: [
      { name: "WiFi", icon: "wifi", available: true },
      { name: "AC", icon: "wind", available: true },
    ],
    powerSupplyHours: 18,
    waterSupply: true,
    agentId: "agent-005",
    isVerified: true,
    isOwnershipVerified: false,
    isPriceReduced: false,
    listedAt: new Date("2026-05-20"),
    createdAt: new Date("2026-05-15"),
  },
  {
    id: "prop-006",
    title: "Yaba Starter Flat",
    description:
      "Affordable 2-bedroom flat near major tech hubs — ideal for young professionals.",
    price: 1800000,
    priceType: "rent",
    bedrooms: 2,
    bathrooms: 2,
    squareFootage: 950,
    address: "7 Herbert Macaulay Way",
    city: "Yaba",
    state: "Lagos",
    country: "Nigeria",
    latitude: 6.5095,
    longitude: 3.3711,
    images: [getMockPropertyImage(5)],
    trustScore: 65,
    trustBreakdown: trustBreakdown(65),
    amenities: [
      { name: "Parking", icon: "car", available: false },
      { name: "Generator", icon: "zap", available: true },
    ],
    powerSupplyHours: 12,
    waterSupply: false,
    agentId: "agent-006",
    isVerified: false,
    isOwnershipVerified: false,
    isPriceReduced: true,
    listedAt: new Date("2026-05-22"),
    createdAt: new Date("2026-05-18"),
  },
];
