"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ChevronLeft, ChevronRight, ImagePlus, Plus, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAgentVerificationStore } from "@/store/useAgentVerificationStore";

const input = "mt-1.5 w-full rounded-lg border border-input bg-white px-3 py-2.5 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/20";
const states = ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"];
const amenities = ["24/7 security","Swimming pool","Gym","Elevator","Parking","CCTV","Gated estate","Playground","Balcony","Waterfront","Garden","Concierge","Fibre internet","Central AC","Pet friendly","Wheelchair access"];
const interiors = ["Fitted kitchen","Walk-in closet","Built-in wardrobes","POP ceiling","Marble floors","Smart home","Home office","Jacuzzi","Boys’ quarters","Store room","Laundry room","Fireplace","Intercom","Serviced apartment","Air conditioning","Water heater","Kitchen island","Pantry"];
export default function ListingForm() { const status = useAgentVerificationStore((s) => s.status); const [step,setStep]=useState(1); const [done,setDone]=useState(false); const [price,setPrice]=useState(""); const [feature,setFeature]=useState(""); const [features,setFeatures]=useState<string[]>([]); const [photos,setPhotos]=useState<string[]>([]); const submit=(e:FormEvent)=>{e.preventDefault(); if(step<5)setStep(step+1);else setDone(true)};
if(status!=="approved") return <Gate />; if(done) return <div className="mx-auto max-w-lg px-4 py-16 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h1 className="mt-4 text-2xl font-bold">Listing submitted</h1><p className="mt-2 text-muted-foreground">Your property is under review and will appear in your listings once approved.</p><Button asChild className="mt-6"><Link href="/dashboard?view=listings">View listings</Link></Button></div>;
return <div className="mx-auto max-w-3xl px-4 py-8"><Link href="/dashboard?view=listings" className="text-sm font-semibold text-muted-foreground hover:text-primary">← Back to listings</Link><h1 className="mt-4 text-3xl font-bold">List a property</h1><p className="mt-1 text-muted-foreground">Save time by completing each section before publishing.</p><div className="mt-6 flex gap-1">{["Basics","Location","Details","Features","Pricing & publish"].map((name,i)=><div key={name} className="flex-1"><div className={`h-1 rounded ${i+1<=step?"bg-primary":"bg-muted"}`}/><p className={`mt-2 text-center text-[10px] font-semibold sm:text-xs ${i+1===step?"text-primary":"text-muted-foreground"}`}>{name}</p></div>)}</div><form onSubmit={submit} className="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm sm:p-7">{step===1&&<Basics/>}{step===2&&<Location/>}{step===3&&<Details/>}{step===4&&<Features photos={photos} setPhotos={setPhotos} feature={feature} setFeature={setFeature} features={features} setFeatures={setFeatures}/>} {step===5&&<Pricing price={price} setPrice={setPrice}/>}<div className="mt-7 flex justify-between border-t border-border pt-5">{step>1?<Button variant="outline" type="button" onClick={()=>setStep(step-1)}><ChevronLeft className="h-4 w-4"/> Back</Button>:<span/>}<Button type="submit">{step===5?"Submit listing":<>Continue <ChevronRight className="h-4 w-4"/></>}</Button></div></form></div> }
function Basics(){return <Section title="Basics" text="Tell clients what you are listing."><Grid><Field label="Property title" placeholder="e.g. Bright 3-bedroom in Lekki"/><Select label="Listing purpose" options={["For sale","For rent"]}/><Select label="Property type" options={["Apartment","Detached house","Semi-detached house","Terraced house","Duplex","Bungalow","Land","Office space","Shop / commercial"]}/><Field label="Property reference (optional)" placeholder="Your internal reference"/></Grid></Section>}
function Location(){return <Section title="Location" text="Your exact address remains private until you approve a viewing."><Grid><Field label="Street address"/><Field label="Neighbourhood"/><Field label="City"/><Select label="State" options={states}/><Field label="Nearest landmark" placeholder="e.g. 3 minutes from Circle Mall"/></Grid><p className="mt-4 rounded-lg bg-primary/5 p-3 text-xs text-muted-foreground">Location privacy: your street address is never displayed publicly without your permission.</p></Section>}
function Details(){return <Section title="Property details" text="Complete the practical details that matter to buyers and tenants."><Grid>{["Bedrooms","Bathrooms","Toilets","Floor area (sqm)","Plot size (sqm)","Number of floors","Parking spaces","Year built","Generator size (kVA)","Solar capacity (kW)","Water storage (litres)"].map(x=><Field key={x} label={x} type="number"/>)}<Select label="Furnished status" options={["Unfurnished","Semi-furnished","Fully furnished"]}/></Grid><div className="mt-4"><p className="text-sm font-semibold">Title documents</p><div className="mt-2 flex flex-wrap gap-3">{["C of O","Survey Plan","Governor’s Consent"].map(x=><label key={x} className="rounded-full border border-border px-3 py-2 text-sm"><input type="checkbox" className="mr-2"/>{x}</label>)}</div></div></Section>}
function Features({photos,setPhotos,feature,setFeature,features,setFeatures}:{photos:string[];setPhotos:(x:string[])=>void;feature:string;setFeature:(x:string)=>void;features:string[];setFeatures:(x:string[])=>void}){return <Section title="Amenities & features" text="Select everything that makes this property stand out."><Checks title="Amenities" items={amenities}/><Checks title="Interior features" items={interiors}/><div className="mt-6"><p className="text-sm font-semibold">Custom features</p><div className="mt-2 flex gap-2"><input value={feature} onChange={e=>setFeature(e.target.value)} className={input.replace("mt-1.5 ","")} placeholder="e.g. Ocean view"/><Button type="button" variant="outline" onClick={()=>{if(feature.trim()){setFeatures([...features,feature.trim()]);setFeature("")}}}><Plus className="h-4 w-4"/></Button></div><div className="mt-2 flex flex-wrap gap-2">{features.map((x,i)=><button type="button" onClick={()=>setFeatures(features.filter((_,idx)=>idx!==i))} key={x} className="rounded-full bg-muted px-3 py-1 text-xs">{x} <X className="inline h-3 w-3"/></button>)}</div></div><label className="mt-6 flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-primary/30 bg-primary/[0.03]"><ImagePlus className="h-6 w-6 text-primary"/><span className="mt-2 text-sm font-semibold">Upload property photos</span><span className="mt-1 text-xs text-muted-foreground">{photos.length?`${photos.length} photo(s) selected`:"Drag and drop or choose files"}</span><input type="file" className="sr-only" accept="image/*" multiple onChange={e=>setPhotos(Array.from(e.target.files??[]).map(f=>f.name))}/></label><Grid><Field label="Video tour URL (optional)" type="url"/><Field label="Virtual tour URL (optional)" type="url"/></Grid></Section>}
function Pricing({price,setPrice}:{price:string;setPrice:(x:string)=>void}){const formatted=price?new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(price)):"₦0";return <Section title="Pricing & publish" text="Review your listing before it is submitted for approval."><Grid><label className="text-sm font-semibold">Asking price<input value={price} onChange={e=>setPrice(e.target.value.replace(/\D/g,""))} inputMode="numeric" className={input} placeholder="0"/><span className="mt-1 block text-xs text-primary">{formatted}</span></label><Field label="Service charge (rent only)" type="number"/></Grid><label className="mt-4 flex items-center gap-2 text-sm font-semibold"><input type="checkbox"/> Price is negotiable</label><label className="mt-4 block text-sm font-semibold">Description<textarea required rows={6} className={input} placeholder="Describe the property, its condition, and why it is a great choice."/></label><div className="mt-5 rounded-xl bg-muted p-4"><p className="font-bold">Listing summary</p><p className="mt-1 text-sm text-muted-foreground">{formatted} · Submitted listings are reviewed for quality and verification before publication.</p></div></Section>}
function Section({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <section><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p><div className="mt-5">{children}</div></section>};function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>};function Field({label,type="text",placeholder}:{label:string;type?:string;placeholder?:string}){return <label className="text-sm font-semibold">{label}<input required={label!=="Property reference (optional)"||undefined} type={type} className={input} placeholder={placeholder}/></label>};function Select({label,options}:{label:string;options:string[]}){return <label className="text-sm font-semibold">{label}<select className={input} defaultValue=""> <option disabled value="">Select an option</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>};function Checks({title,items}:{title:string;items:string[]}){return <div className="mt-5"><p className="text-sm font-semibold">{title}</p><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{items.map(x=><label key={x} className="text-xs text-muted-foreground"><input type="checkbox" className="mr-1.5"/>{x}</label>)}</div></div>};function Gate(){return <div className="mx-auto max-w-lg px-4 py-16 text-center"><h1 className="text-2xl font-bold">Verification required</h1><p className="mt-2 text-muted-foreground">Only approved agents can list properties.</p><Button asChild className="mt-6"><Link href="/agent/signup">Complete verification</Link></Button></div>}
